name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore ./PojistovnaFullAspPrzeczek/PojistovnaFullAspPrzeczek.sln

    - name: Build
      run: dotnet build ./PojistovnaFullAspPrzeczek/PojistovnaFullAspPrzeczek.sln --no-restore

    - name: Run tests
      run: dotnet test ./PojistovnaFullAspPrzeczek.Tests.Unit.xUnit/PojistovnaFullAspPrzeczek.Tests.Unit.xUnit.csproj --no-build --verbosity normal